-- This module serves as the root of the `ClassificationOfSubgroups` library.
-- Import modules here that should be built as part of the library.
--ClassificationOfSubgroups/Ch2_PGLIsoPSLOverAlgClosedField.lean/ProjectiveGeneralLinearGroup.lean
import ClassificationOfSubgroups.Ch4_PGLIsoPSLOverAlgClosedField.ProjectiveGeneralLinearGroup
import ClassificationOfSubgroups.Ch5_PropertiesOfSLOverAlgClosedField.S1_SpecialMatrices
import ClassificationOfSubgroups.Ch5_PropertiesOfSLOverAlgClosedField.S2_SpecialSubgroups
import ClassificationOfSubgroups.Ch5_PropertiesOfSLOverAlgClosedField.S3_JordanNormalFormOfSL
import ClassificationOfSubgroups.Ch5_PropertiesOfSLOverAlgClosedField.S4_PropertiesOfCentralizers
import ClassificationOfSubgroups.Ch5_PropertiesOfSLOverAlgClosedField.S5_PropertiesOfNormalizers
import ClassificationOfSubgroups.Ch5_PropertiesOfSLOverAlgClosedField.S6_TripleTransitivity
import ClassificationOfSubgroups.Ch6_MaximalAbelianSubgroupClassEquation.S1_ElementaryAbelian
import ClassificationOfSubgroups.Ch6_MaximalAbelianSubgroupClassEquation.S2_A_MaximalAbelianSubgroup
import ClassificationOfSubgroups.Ch6_MaximalAbelianSubgroupClassEquation.S2_B_MaximalAbelianSubgroup
import ClassificationOfSubgroups.Ch6_MaximalAbelianSubgroupClassEquation.S3_NoncenterClassEquation
import ClassificationOfSubgroups.Ch6_MaximalAbelianSubgroupClassEquation.S4_CaseArithmetic
import ClassificationOfSubgroups.Ch6_MaximalAbelianSubgroupClassEquation.S5_NumericClassEquation
import ClassificationOfSubgroups.Ch7_GroupRecognition
import ClassificationOfSubgroups.Ch7_DicksonsClassificationTheorem
import ClassificationOfSubgroups.Ch8_CharZeroEmbedding
import ClassificationOfSubgroups.Ch8_CharZero
