-- This module serves as the root of the `ClassificationOfSubgroups` library.
-- Import modules here that should be built as part of the library.
--ClassificationOfSubgroups/Ch2_PGLIsoPSLOverAlgClosedField.lean/ProjectiveGeneralLinearGroup.lean
import ClassificationOfSubgroups.Ch2_PGLIsoPSLOverAlgClosedField.ProjectiveGeneralLinearGroup
import ClassificationOfSubgroups.Ch3_PropertiesOfSLOverAlgClosedField.S1_SpecialMatrices
import ClassificationOfSubgroups.Ch3_PropertiesOfSLOverAlgClosedField.S2_SpecialSubgroups
import ClassificationOfSubgroups.Ch3_PropertiesOfSLOverAlgClosedField.S3_JordanNormalFormOfSL
import ClassificationOfSubgroups.Ch4_MaximalAbelianSubgroupClassEquation.ElementaryAbelian
import ClassificationOfSubgroups.Ch4_MaximalAbelianSubgroupClassEquation.MaximalAbelianSubgroup
